name: Build and Deploy Frontend to Azure Web App - legacy-hands-of-hope

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_43C66C0C166B4C9F9DE6597F347E2B08 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A3B99DEC61184710847D0B141CB83A6D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E944AE256E74470DA30E80C670BB8867 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: legacy-hands-of-hope
          slot-name: Production
          package: .
